# Generated by Django 4.2.7 on 2023-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinvetory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
