# Generated by Django 4.2.7 on 2023-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
